
from tkinter import*
import tkinter as tk
root=Tk()
root.geometry("600x600")
name_var=tk.StringVar()
pass_var=tk.StringVar()
def submit():
    name=name_var.get()
    password=pass_var.get()
    print("the name is:"+name)
    print("the password is:"+password)
    label_name=tk.Label(text=name)
    label_name.grid(row=4,column=4)
    label_pass=tk.Label(text=password)
    label_pass.grid(row=5,column=4)
    name_var.set("")
    pass_var.set("")
name_label=tk.Label(root,text='username',font=('arial',10,'bold'))
name_entry=tk.Entry(root,textvariable=name_var,font=('arial',10,'normal'))
pass_label=tk.Label(root,text='password',font=('arial',10,'bold'))
pass_entry=tk.Entry(root,textvariable=pass_var,font=('arial',10,'normal'),show='*')
sub_btn=tk.Button(root,text="submit",command=submit)
name_label.grid(row=0,column=0)
name_entry.grid(row=0,column=1)
pass_label.grid(row=1,column=0)
pass_entry.grid(row=1,column=1)
sub_btn.grid(row=2,column=1)

root.mainloop()